import 'package:flirt/core/module/home/application/service/cubit/home_dto.dart';

final List<Prompt> promptList = <Prompt>[
  Prompt(one: 'Tooth', three: 'Tooth Fairy'),
  Prompt(one: 'Dog', three: 'Hot Dog'),
  Prompt(one: 'Cake', three: 'Birthday Cake'),
  Prompt(one: 'Book', three: 'Comic Book'),
  Prompt(one: 'Fish', three: 'Fish Tank'),
  Prompt(one: 'Car', three: 'Race Car'),
  Prompt(one: 'Box', three: 'Cardboard Box'),
  Prompt(one: 'Key', three: 'Car Key'),
  Prompt(one: 'Cup', three: 'Coffee Cup'),
  Prompt(one: 'Tree', three: 'Christmas Tree'),
  Prompt(one: 'Moon', three: 'Full Moon'),
  Prompt(one: 'Sun', three: 'Sunlight'),
  Prompt(one: 'Ball', three: 'Basketball'),
  Prompt(one: 'Light', three: 'Stop Light'),
  Prompt(one: 'Red', three: 'Red Horse'),
  Prompt(one: 'Eye', three: 'Eye Patch'),
  Prompt(one: 'Wet', three: 'Wet Dream'),
  Prompt(one: 'Pillow', three: 'Pillow Talk'),
  Prompt(one: 'One', three: 'One Nightstand'),
  Prompt(one: 'Sugar', three: 'Sugar Daddy'),
  Prompt(one: 'High', three: 'High Heels'),
  Prompt(one: 'Netflix', three: 'Netflix and Chill'),
  Prompt(one: 'Couch', three: 'Couch Surfing'),
  Prompt(one: 'Deep', three: 'Deep Throat'),
  Prompt(one: 'Pole', three: 'Pole Dance'),
  Prompt(one: 'Forbidden', three: 'Forbidden Fruit'),
  Prompt(one: 'Blind', three: 'Blind Date'),
  Prompt(one: 'Black', three: 'Black Widow'),
  Prompt(one: 'Rice', three: 'Rice Cooker'),
  Prompt(one: 'Pancit', three: 'Pancit Canton'),
  Prompt(one: 'Chat', three: 'ChatGPT'),
  Prompt(one: 'Git', three: 'Github'),
  Prompt(one: 'Java', three: 'Javascript'),
  Prompt(one: 'Chicken', three: 'Chicken Adobo'),
  Prompt(one: 'Java', three: 'Javascript'),
  Prompt(one: 'Hex', three: 'Hex Code'),
  Prompt(one: 'Merge', three: 'Merge Conflict'),
  Prompt(one: 'Ass', three: 'Asana'),
  Prompt(one: 'Ice', three: 'Ice Candy'),
  Prompt(one: 'Chic', three: 'Chicken Joy'),
  Prompt(one: 'Hang', three: 'Hangover'),
  Prompt(one: 'Boy', three: 'Boy Abunda'),
  Prompt(one: 'G', three: 'Gmall'),
  Prompt(one: 'Einstein', three: 'Albert Einstein'),
  Prompt(one: 'Hot', three: 'Hot Sauce'),
  Prompt(one: 'Burger', three: 'Burger Mcdo'),
  Prompt(one: 'Kai', three: 'Kai Sotto'),
  Prompt(one: 'Rock', three: 'Rockstar'),
  Prompt(one: 'Sand', three: 'Sandbox'),
  Prompt(one: 'Tree', three: 'Treehouse'),
  Prompt(one: 'Phone', three: 'iPhone'),
  Prompt(one: 'Ring', three: 'Wedding Ring'),
  Prompt(one: 'Light', three: 'Flashlight'),
  Prompt(one: 'Water', three: 'Waterfall'),
  Prompt(one: 'Air', three: 'Airplane'),
  Prompt(one: 'Fish', three: 'Goldfish'),
  Prompt(one: 'Car', three: 'Race Car'),
  Prompt(one: 'Train', three: 'Bullet Train'),
  Prompt(one: 'Plane', three: 'Airplane'),
  Prompt(one: 'Key', three: 'Keyboard'),
  Prompt(one: 'Mouse', three: 'Mickey Mouse'),
  Prompt(one: 'House', three: 'House Party'),
  Prompt(one: 'Glass', three: 'Sunglasses'),
  Prompt(one: 'Snow', three: 'Snowman'),
  Prompt(one: 'Bee', three: 'Beekeeper'),
  Prompt(one: 'Ship', three: 'Spaceship'),
  Prompt(one: 'King', three: 'Lion King'),
  Prompt(one: 'Queen', three: 'Queen Bee'),
  Prompt(one: 'Pop', three: 'Lollipop'),
  Prompt(one: 'Egg', three: 'Eggplant'),
  Prompt(one: 'Street', three: 'Sesame Street'),
  Prompt(one: 'Card', three: 'Birthday Card'),
  Prompt(one: 'Drum', three: 'Drumstick'),
  Prompt(one: 'Rock', three: 'The Rock'),
  Prompt(one: 'Iron', three: 'Iron Man'),
  Prompt(one: 'Spider', three: 'Spider-Man'),
  Prompt(one: 'Harry', three: 'Harry Potter'),
  Prompt(one: 'Hulk', three: 'Incredible Hulk'),
  Prompt(one: 'Sponge', three: 'SpongeBob'),
  Prompt(one: 'Coco', three: 'Coco Martin'),
];
